### ISSUE TITLE
Plans on uploading the code for this paper?

### ISSUE THREAD

**Issue by vr25** [GeminiLn/EarningsCall_Dataset#2]

**Comment by LucasAndLevinAndJadon** [comment]
Agree. Please upload the code ,otherwise it is useless to replicate.

**Comment by GeminiLn** [comment]
Hi, sorry I overlooked this issue before. I usually receive emails directly sent to me about the paper and dataset.

We didn't release the code because we think it's not necessary. The model itself is described in our paper and is quite straightforward. It can be easily implemented with PyTorch or TensorFlow for experienced computer scientists. But please let us know if you come across any problem with the implementation and I'd like to help.

**Comment by 1390806607** [comment]
@GeminiLn  Hello, could you please share the data on stock price volatility following earnings conference calls mentioned in the paper? Thank you!
